--------------------------------------------------------
--  DDL for Table CLIST
--------------------------------------------------------

  CREATE TABLE "JOB"."CLIST" 
   (	"C_ENO" NUMBER(20,0), 
	"C_NAME" VARCHAR2(400 BYTE), 
	"C_POSTNAME" VARCHAR2(400 BYTE), 
	"C_CAREER" VARCHAR2(200 BYTE), 
	"C_CONDITION" VARCHAR2(200 BYTE), 
	"C_DAY" VARCHAR2(200 BYTE), 
	"C_JOBNO" NUMBER(20,0), 
	"C_LINK" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CLIST_CNO
--------------------------------------------------------

  CREATE UNIQUE INDEX "JOB"."PK_CLIST_CNO" ON "JOB"."CLIST" ("C_ENO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CLIST
--------------------------------------------------------

  ALTER TABLE "JOB"."CLIST" ADD CONSTRAINT "PK_CLIST_CNO" PRIMARY KEY ("C_ENO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JOB"."CLIST" MODIFY ("C_JOBNO" NOT NULL ENABLE);
  ALTER TABLE "JOB"."CLIST" MODIFY ("C_POSTNAME" NOT NULL ENABLE);
  ALTER TABLE "JOB"."CLIST" MODIFY ("C_NAME" NOT NULL ENABLE);
