--------------------------------------------------------
--  DDL for Table EDUCATIONS
--------------------------------------------------------

  CREATE TABLE "JOB"."EDUCATIONS" 
   (	"ENO" NUMBER(20,0), 
	"TITLE" VARCHAR2(500 BYTE), 
	"IMGSRC" VARCHAR2(500 BYTE), 
	"ACADEMY_NAME" VARCHAR2(60 BYTE), 
	"ACADEMY_PHONE" VARCHAR2(15 BYTE), 
	"ACADEMY_ADD" VARCHAR2(100 BYTE), 
	"EDU_FIELD" VARCHAR2(150 BYTE), 
	"EDU_TYPE" VARCHAR2(30 BYTE), 
	"EDU_PROCESS" VARCHAR2(400 BYTE), 
	"EDU_COUNT" VARCHAR2(10 BYTE), 
	"EDU_PERIOD" VARCHAR2(30 BYTE), 
	"EDU_LOCATION" VARCHAR2(50 BYTE), 
	"EDU_PRICE" VARCHAR2(20 BYTE), 
	"EDU_PRIVILEGE" VARCHAR2(300 BYTE), 
	"EDU_APP_PERIOD" VARCHAR2(20 BYTE), 
	"EDU_DELETEYN" VARCHAR2(2 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EDUCATIONS_ENO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JOB"."EDUCATIONS_ENO_PK" ON "JOB"."EDUCATIONS" ("ENO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EDUCATIONS
--------------------------------------------------------

  ALTER TABLE "JOB"."EDUCATIONS" ADD CONSTRAINT "EDUCATIONS_ENO_PK" PRIMARY KEY ("ENO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
