--------------------------------------------------------
--  DDL for Table RESUME
--------------------------------------------------------

  CREATE TABLE "JOB"."RESUME" 
   (	"R_NO" NUMBER, 
	"R_TYPE" VARCHAR2(100 BYTE), 
	"R_NAME" VARCHAR2(200 BYTE), 
	"R_EX" VARCHAR2(500 BYTE), 
	"IMAGEFILE" VARCHAR2(200 BYTE), 
	"FILENAME" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
